# version: '3'

services:
  sportino-front:
    image: sportino-front
    container_name: sportino-front
    environment:
      - VIRTUAL_HOST=sportino.com.ar
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sportino.com.ar
    networks:
      - main_network
    mem_limit: 4096m
    mem_reservation: 2048m
    build:
      context: .
      dockerfile: Dockerfile

networks:
  main_network:
    external: true
