name: Deploy Angular App to Linode

on:
  push:
    branches: [master]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build 

      - name: Deploy to Linode via SSH
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.LINODE_HOST }}  # IP del servidor Linode
          username: ${{ secrets.LINODE_USER }}  # Ej: "root"
          key: ${{ secrets.LINODE_SSH_KEY }}  # Clave privada SSH
          source: "dist/*"  # Carpeta de build de Angular
          target: "/var/www/tu-app"  # Ruta en Linode donde se aloja la app
